import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import LanguageProvider from "@/hooks/useLanguage";
import MenuProvider from "@/hooks/useMenu";
import ThemeProvider from "@/hooks/useTheme";
import LayoutContent from "./LayoutContent";
import HeaderApp from "@/components/HeaderApp";
import { ShipProvider } from "../../context/useShip";
import { SphereProvider } from "../../context/useSphere";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <MenuProvider>
        <LanguageProvider>
          <ShipProvider>
            <SphereProvider>
              <html lang="en">
                <body
                  className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                >
                  <HeaderApp />
                  <LayoutContent> {children}</LayoutContent>
                </body>
              </html>
            </SphereProvider>
          </ShipProvider>
        </LanguageProvider>
      </MenuProvider>
    </ThemeProvider>
  );
}
